import {Component, OnInit, ViewChild} from '@angular/core';
import {GanttEditorComponent, GanttEditorOptions} from 'ng-gantt';
import {NgxCaptureService} from 'ngx-capture';

@Component({
  selector: 'app-gantt-ui',
  templateUrl: './gantt-ui.component.html',
  styleUrls: ['./gantt-ui.component.css']
})
export class GanttUiComponent implements OnInit {

  @ViewChild('editor')
  editor: GanttEditorComponent = new GanttEditorComponent;
  public editorOptions: GanttEditorOptions = new GanttEditorOptions;
  public data: any;
  imgBase64: any=''

  constructor(private captureService:NgxCaptureService) { }

  ngOnInit(): void {

    this.data = this.initialData();
    this.editorOptions = {
      vFormat: "day",
      vEditable: true,
      vShowDur: 0,
      vShowStartDate: 0,
      vShowEndDate: 0,
      vShowRes: 0,
      vFormatArr: ['Week', 'Month', 'Quarter'],
      vQuarterColWidth: 60,
      vRowHeight: 30,
      vShowComp: 0,

      vEventsChange: {
        taskname: () => {
          console.log("taskname");
        }
      }
    };



  }
  @ViewChild('screen', { static: true }) screen: any;

  capture()
  {
    this.captureService.getImage(this.screen.nativeElement, true).toPromise().then(img=>{
      console.log(img);
      this.imgBase64=img;
      this.save('GanttChart');

    })
  }

  DataURIToBlob(dataURI: string) {
    const splitDataURI = dataURI.split(',');
    const byteString = splitDataURI[0].indexOf('base64') >= 0 ? atob(splitDataURI[1]) : decodeURI(splitDataURI[1]);
    const mimeString = splitDataURI[0].split(':')[1].split(';')[0];
    const ia = new Uint8Array(byteString.length)
    for (let i = 0; i < byteString.length; i++)
        ia[i] = byteString.charCodeAt(i);

        return new Blob([ia], { type: mimeString });
}


  save(fileName: string){
    var a = document.createElement('a');
    var file = this.DataURIToBlob(this.imgBase64);
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();

  }

  initialData(){
    return [
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 104,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 81,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 95,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 31,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 11,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 12,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 56,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 54,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 7,
        "pLink": null,
        "pMile": 0,
        "pName": "Pazhavanthangal Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 15,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 8,
        "pLink": null,
        "pMile": 0,
        "pName": "Tambaram Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 102,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 44,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 75,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 42,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 9,
        "pLink": null,
        "pMile": 0,
        "pName": "Crompet Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 52,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 33,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 71,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 53,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 101,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 3,
        "pLink": null,
        "pMile": 0,
        "pName": "Pallavaram Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 1,
        "pLink": null,
        "pMile": 0,
        "pName": "Arden Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-03-24",
        "pGroup": 0,
        "pID": 16,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 82,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 91,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 43,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 85,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 34,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 64,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 24,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 55,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 6,
        "pLink": null,
        "pMile": 0,
        "pName": "Meenambakkam Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 93,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 94,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 74,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 96,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 32,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 14,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpurple",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2021-05-01",
        "pGroup": 0,
        "pID": 84,
        "pLink": null,
        "pMile": 0,
        "pName": "Secondary Structure ( 11-Jul-20 to 1-May-21 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-07-11",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 36,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 10,
        "pLink": null,
        "pMile": 0,
        "pName": "Tirusulam Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 51,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 5,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 103,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 2,
        "pLink": null,
        "pMile": 0,
        "pName": "Perungalathur Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 106,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 21,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 13,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 1,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 26,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 62,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 61,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 66,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 86,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 5,
        "pLink": null,
        "pMile": 0,
        "pName": "Guindy Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 76,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 25,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 83,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 8,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 92,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 9,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 63,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 105,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 10,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "ggroupblack",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": null,
        "pGroup": 1,
        "pID": 4,
        "pLink": null,
        "pMile": 0,
        "pName": "St Thomas Mount Station",
        "pNotes": null,
        "pOpen": 1,
        "pParent": 0,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": null,
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2018-12-20",
        "pGroup": 0,
        "pID": 41,
        "pLink": null,
        "pMile": 0,
        "pName": "Piling Works ( 18-Apr-18 to 20-Dec-18 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-04-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 73,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 45,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 35,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 3,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskred",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2024-03-24",
        "pGroup": 0,
        "pID": 46,
        "pLink": null,
        "pMile": 0,
        "pName": "Architectural Finishes ( 12-Aug-20 to 24-Mar-24 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 4,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-08-12",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskpink",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2022-01-14",
        "pGroup": 0,
        "pID": 65,
        "pLink": null,
        "pMile": 0,
        "pName": "MEP Fit Off ( 18-Sep-20 to 14-Jan-22 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 6,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2020-09-18",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 72,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 7,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskgreen",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2019-06-14",
        "pGroup": 0,
        "pID": 22,
        "pLink": null,
        "pMile": 0,
        "pName": "Excavation Works ( 10-Aug-18 to 14-Jun-19 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2018-08-10",
        "sector": null
      },
      {
        "category": null,
        "pBarText": null,
        "pCaption": null,
        "pClass": "gtaskyellow",
        "pComp": 0,
        "pCost": 0,
        "pDepend": null,
        "pEnd": "2020-05-08",
        "pGroup": 0,
        "pID": 23,
        "pLink": null,
        "pMile": 0,
        "pName": "Primary Structure ( 8-Nov-19 to 8-May-20 )",
        "pNotes": null,
        "pOpen": 0,
        "pParent": 2,
        "pPlanEnd": null,
        "pPlanStart": null,
        "pRes": null,
        "pStart": "2019-11-08",
        "sector": null
      }
    ];
  }



}
